# name: CI -> Deploy to hosting
# on:
#   push:
#     branches: [main]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./
#     steps:
#       - uses: actions/checkout@v4
#       - name: Install dependencies and build
#         run: |
#           npm install
#           npm run build
#       # Here is the deployment action
#       - name: Upload from dist via FTP
#         uses: airvzxf/ftp-deployment-action@latest
#         with:
#           server: ${{ secrets.FTP_SERVER }}
#           user: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           local_dir: "./dist"
#           remote_dir: "/nii-vn.ru/docs"
#           delete: true

name: CI -> Deploy to hosting
on:
  push:
    branches: [ main, test ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build (production)
        if: github.ref == 'refs/heads/main'
        run: |
          npm install
          npm run build:production

      - name: Install dependencies and build (test)
        if: github.ref == 'refs/heads/test'
        run: |
          npm install
          npm run build:test

      # Deploy only on main branch
      - name: Upload from dist via FTP
        if: github.ref == 'refs/heads/main'
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./dist"
          remote_dir: "/nii-vn.ru/docs"
          delete: true
